"""initial migration

Revision ID: 10502b6e1ddd
Revises: 
Create Date: 2025-06-05 18:47:27.522538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10502b6e1ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtsp_stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtsp_stream', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
