"""remove cascade from rtsp_sop_association

Revision ID: 3b21325d3c22
Revises: 3e585c4d0dcf
Create Date: 2025-05-29 17:13:30.807523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b21325d3c22'
down_revision = '3e585c4d0dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtsp_sop_association', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rtsp_sop_association_sop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rtsp_sop_association_rtsp_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sop', ['sop_id'], ['id'])
        batch_op.create_foreign_key(None, 'rtsp_stream', ['rtsp_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtsp_sop_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rtsp_sop_association_rtsp_id_fkey'), 'rtsp_stream', ['rtsp_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('rtsp_sop_association_sop_id_fkey'), 'sop', ['sop_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
