"""add description column to ai_model

Revision ID: 750ffab7522f
Revises: 
Create Date: 2025-05-27 17:47:48.946089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750ffab7522f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('desc')

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rtsp_stream', ['rtsp_id'], ['id'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('desc')

    with op.batch_alter_table('rtsp_sop_association', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'rtsp_stream', ['rtsp_id'], ['id'])

    with op.batch_alter_table('rtsp_stream', schema=None) as batch_op:
        batch_op.alter_column('rtsp_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('coco_link',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('rtsp_stream_rtsp_url_key'), type_='unique')

    with op.batch_alter_table('sop', schema=None) as batch_op:
        batch_op.drop_column('rtsp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtsp_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('rtsp_stream', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('rtsp_stream_rtsp_url_key'), ['rtsp_url'])
        batch_op.alter_column('coco_link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('rtsp_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('rtsp_sop_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ai_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
