"""Add structured_output to SOP and change output to JSON in Analysis

Revision ID: e8549d10daf1
Revises: 10502b6e1ddd
Create Date: 2025-06-16 18:07:56.286211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8549d10daf1'
down_revision = '10502b6e1ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        # Drop existing data
        batch_op.execute('DELETE FROM analysis')  # This will remove all data in the analysis table
        batch_op.alter_column('output',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='output::json',
               existing_nullable=True)

    with op.batch_alter_table('sop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_output', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sop', schema=None) as batch_op:
        batch_op.drop_column('structured_output')

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('output',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
